export default {
    /// === GET ALL AUTHORS ===
    GET_ALL_AUTHORS_ASYNC: 'GET_ALL_AUTHORS_ASYNC',
    GET_ALL_AUTHORS_SUCCEED: 'GET_ALL_AUTHORS_SUCCEED',
    GET_ALL_AUTHOR_FAILED: 'GET_ALL_AUTHOR_FAILED',

    /// === GET AUTHOR DETAIL ===
    GET_AUTHOR_DETAIL_ASYNC: 'GET_AUTHOR_DETAIL_ASYNC',
    GET_AUTHOR_DETAIL_SUCCEED: 'GET_AUTHOR_DETAIL_SUCCEED',
    GET_AUTHOR_DETAIL_FAILED: 'GET_AUTHOR_DETAIL_FAILED',

    /// === CREATE AUTHOR ===
    CREATE_AUTHOR_ASYNC: 'CREATE_AUTHOR_ASYNC',
    CREATE_AUTHOR_SUCCEED: 'CREATE_AUTHOR_SUCCEED',
    CREATE_AUTHOR_FAILED: 'CREATE_AUTHOR_FAILED',

    /// === UPDATE AUTHOR ===
    UPDATE_AUTHOR_ASYNC: 'UPDATE_AUTHOR_ASYNC',
    UPDATE_AUTHOR_SUCCEED: 'UPDATE_AUTHOR_SUCCEED',
    UPDATE_AUTHOR_FAILED: 'UPDATE_AUTHOR_FAILED',

    /// === DELETE AUTHOR ===
    DELETE_AUTHOR_ASYNC: 'DELETE_AUTHOR_ASYNC',
    DELETE_AUTHOR_SUCCEED: 'DELETE_AUTHOR_SUCCEED',
    DELETE_AUTHOR_FAILED: 'DELETE_AUTHOR_FAILED',

    /// === NON-SERVER ACTION ===
    CLEAR_CURRENT_AUTHOR: 'CLEAR_CURRENT_AUTHOR'
}