export default {
    /// === GET ALL GENRES ===
    GET_ALL_GENRES_ASYNC: 'GET_ALL_GENRES_ASYNC',
    GET_ALL_GENRES_SUCCEED: 'GET_ALL_GENRES_SUCCEED',
    GET_ALL_GENRE_FAILED: 'GET_ALL_GENRE_FAILED',

    /// === GET GENRE DETAIL ===
    GET_GENRE_DETAIL_ASYNC: 'GET_GENRE_DETAIL_ASYNC',
    GET_GENRE_DETAIL_SUCCEED: 'GET_GENRE_DETAIL_SUCCEED',
    GET_GENRE_DETAIL_FAILED: 'GET_GENRE_DETAIL_FAILED',

    /// === CREATE GENRE ===
    CREATE_GENRE_ASYNC: 'CREATE_GENRE_ASYNC',
    CREATE_GENRE_SUCCEED: 'CREATE_GENRE_SUCCEED',
    CREATE_GENRE_FAILED: 'CREATE_GENRE_FAILED',

    /// === UPDATE GENRE ===
    UPDATE_GENRE_ASYNC: 'UPDATE_GENRE_ASYNC',
    UPDATE_GENRE_SUCCEED: 'UPDATE_GENRE_SUCCEED',
    UPDATE_GENRE_FAILED: 'UPDATE_GENRE_FAILED',

    /// === DELETE GENRE ===
    DELETE_GENRE_ASYNC: 'DELETE_GENRE_ASYNC',
    DELETE_GENRE_SUCCEED: 'DELETE_GENRE_SUCCEED',
    DELETE_GENRE_FAILED: 'DELETE_GENRE_FAILED',

    /// === NON-SERVER ACTION ===
    CLEAR_CURRENT_GENRE: 'CLEAR_CURRENT_GENRE'
}