export default {
    /// === GET ALL BOOKS ===
    GET_ALL_BOOKS_ASYNC: 'GET_ALL_BOOKS_ASYNC',
    GET_ALL_BOOKS_SUCCEED: 'GET_ALL_BOOKS_SUCCEED',
    GET_ALL_BOOKS_FAILED: 'GET_ALL_BOOKS_FAILED',

    /// === GET BOOK DETAIL ===
    GET_BOOK_DETAIL_ASYNC: 'GET_BOOK_DETAIL_ASYNC',
    GET_BOOK_DETAIL_SUCCEED: 'GET_BOOK_DETAIL_SUCCEED',
    GET_BOOK_DETAIL_FAILED: 'GET_BOOK_DETAIL_FAILED',

    /// === CREATE BOOK ===
    CREATE_BOOK_ASYNC: 'CREATE_BOOK_ASYNC',
    CREATE_BOOK_SUCCEED: 'CREATE_BOOK_SUCCEED',
    CREATE_BOOK_FAILED: 'CREATE_BOOK_FAILED',

    /// === UPDATE BOOK ===
    UPDATE_BOOK_ASYNC: 'UPDATE_BOOK_ASYNC',
    UPDATE_BOOK_SUCCEED: 'UPDATE_BOOK_SUCCEED',
    UPDATE_BOOK_FAILED: 'UPDATE_BOOK_FAILED',

    /// === DELETE BOOK ===
    DELETE_BOOK_ASYNC: 'DELETE_BOOK_ASYNC',
    DELETE_BOOK_SUCCEED: 'DELETE_BOOK_SUCCEED',
    DELETE_BOOK_FAILED: 'DELETE_BOOK_FAILED',

    /// === NON-SERVER ACTION ===
    CLEAR_CURRENT_BOOK: 'CLEAR_CURRENT_BOOK'
}